local:
  service: Disk
  root: <%= ENV['LOCAL_DISK_STORAGE_ROOT'] %>

test:
  service: Disk
  root: <%= ENV['LOCAL_DISK_STORAGE_ROOT'] %>

linode:
  service: S3
  endpoint: <%= ENV.fetch("S3_ENDPOINT") %>
  region: <%= ENV.fetch("S3_REGION") %>
  access_key_id: <%= ENV.fetch("S3_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("S3_SECRET_ACCESS_KEY") %>
  bucket: <%= ENV.fetch("S3_BUCKET") %>
