require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/metadata_namespaces", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MetadataNamespace. As you add validations to MetadataNamespace, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MetadataNamespace.create! valid_attributes
      get metadata_namespaces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      metadata_namespace = MetadataNamespace.create! valid_attributes
      get metadata_namespace_url(metadata_namespace)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_metadata_namespace_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      metadata_namespace = MetadataNamespace.create! valid_attributes
      get edit_metadata_namespace_url(metadata_namespace)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MetadataNamespace" do
        expect {
          post metadata_namespaces_url, params: { metadata_namespace: valid_attributes }
        }.to change(MetadataNamespace, :count).by(1)
      end

      it "redirects to the created metadata_namespace" do
        post metadata_namespaces_url, params: { metadata_namespace: valid_attributes }
        expect(response).to redirect_to(metadata_namespace_url(MetadataNamespace.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MetadataNamespace" do
        expect {
          post metadata_namespaces_url, params: { metadata_namespace: invalid_attributes }
        }.to change(MetadataNamespace, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post metadata_namespaces_url, params: { metadata_namespace: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested metadata_namespace" do
        metadata_namespace = MetadataNamespace.create! valid_attributes
        patch metadata_namespace_url(metadata_namespace), params: { metadata_namespace: new_attributes }
        metadata_namespace.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the metadata_namespace" do
        metadata_namespace = MetadataNamespace.create! valid_attributes
        patch metadata_namespace_url(metadata_namespace), params: { metadata_namespace: new_attributes }
        metadata_namespace.reload
        expect(response).to redirect_to(metadata_namespace_url(metadata_namespace))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        metadata_namespace = MetadataNamespace.create! valid_attributes
        patch metadata_namespace_url(metadata_namespace), params: { metadata_namespace: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested metadata_namespace" do
      metadata_namespace = MetadataNamespace.create! valid_attributes
      expect {
        delete metadata_namespace_url(metadata_namespace)
      }.to change(MetadataNamespace, :count).by(-1)
    end

    it "redirects to the metadata_namespaces list" do
      metadata_namespace = MetadataNamespace.create! valid_attributes
      delete metadata_namespace_url(metadata_namespace)
      expect(response).to redirect_to(metadata_namespaces_url)
    end
  end
end
