shared:
  catalogue_default_page_size: 20
  system_review_period: 365 #days
  default_models:
    rp: <%= ENV["DEFAULT_RP"] %> #IRD System
    platform: <%= ENV["DEFAULT_PLATFORM"] %>
    system_user: <%= ENV["SYSTEM_USER"] %>
  default_attributes:
    system_category: "repository"
  network_check_failure:
    error_count_threshold: <%= ENV.fetch("ERROR_COUNT_THRESHOLD",3).to_i %>
    error_duration_threshold: <%= ENV.fetch("ERROR_DURATION_THRESHOLD",30).to_i %> #days
  ark:
    naan: 15398
    shoulder: x1
  repoid_schemes:
    ird:
      display: false
      link_to_source: false
      http_prefix: https://ird.coar-repositories.org/systems/
      http_suffix:
    opendoar:
      display: true
      link_to_source: true
      http_prefix: https://v2.sherpa.ac.uk/id/repository/
      http_suffix:
    re3data:
      display: true
      link_to_source: true
      http_prefix: https://www.re3data.org/repository/
      http_suffix:
    roar:
      display: true
      link_to_source: true
      http_prefix: https://roar.eprints.org/
      http_suffix:
    lyrasis:
      display: true
      link_to_source: false
      http_prefix: https://registry.lyrasis.org/entry/
      http_suffix:
    oai:
      display: true
      link_to_source: false
      http_prefix:
      http_suffix:
    ark:
      display: false
      link_to_source: true
      http_prefix: https://n2t.net/
      http_suffix:
  locales:
    en:
      language: English
      flag: gb
    es:
      language: Español
      flag: es
    fr:
      language: Français
      flag: fr
    ja:
      language: 日本語
      flag: jp
    pt:
      language: Português
      flag: pt
    tr:
      language: Türkçe
      flag: tr
    zh-CN:
      language: 中文
      flag: cn
  media_types:
    research-articles:
      identifier: "http://purl.org/coar/resource_type/c_2df8fbb1"
    research-data:
      identifier: "http://purl.org/coar/resource_type/c_ddb1"
    books:
      identifier: "http://purl.org/coar/resource_type/c_2f33"
    conference-papers:
      identifier: "http://purl.org/coar/resource_type/c_5794"
    images:
      identifier: "http://purl.org/coar/resource_type/c_c513"
    learning-objects:
      identifier: "http://purl.org/coar/resource_type/c_e059"
    multimedia:
      identifier: "http://purl.org/coar/resource_type/multimedia"
    other:
      identifier: "http://purl.org/coar/resource_type/c_1843"
    patents:
      identifier: "http://purl.org/coar/resource_type/c_15cd"
    software:
      identifier: "http://purl.org/coar/resource_type/c_5ce6"
    theses:
      identifier: "http://purl.org/coar/resource_type/c_46ec"
  labels:
    duplicate:
      restricted: false
    out-of-scope:
      restricted: false
    candidate-defunct:
      restricted: true
    flag:
      restricted: false
    defunct:
      restricted: false
    candidate-out-of-scope:
      restricted: true


