shared:
  catalogue_default_page_size: 20
  system_review_period: 365 #days
  default_models:
    rp_for_published_records: <%= ENV["RP_FOR_PUBLISHED_RECORDS"] %> #COAR
    rp_for_archived_records: <%= ENV["RP_FOR_ARCHIVED_RECORDS"] %> #IRD System
    platform: <%= ENV["DEFAULT_PLATFORM"] %>
  network_check_failure:
    error_count_threshold: <%= ENV.fetch("ERROR_COUNT_THRESHOLD",3).to_i %>
    error_duration_threshold: <%= ENV.fetch("ERROR_DURATION_THRESHOLD",30).to_i %> #days
  repoid_schemes:
    ird:
      link_to_source: false
      http_prefix: https://ird.coar-repositories.org/systems/
      http_suffix:
    opendoar:
      link_to_source: true
      http_prefix: https://v2.sherpa.ac.uk/id/repository/
      http_suffix:
    re3data:
      link_to_source: true
      http_prefix: https://www.re3data.org/repository/
      http_suffix:
    roar:
      link_to_source: true
      http_prefix: https://roar.eprints.org/
      http_suffix:
    lyrasis:
      link_to_source: false
      http_prefix: https://registry.lyrasis.org/entry/
      http_suffix:
    oai:
      link_to_source: false
      http_prefix:
      http_suffix:
  locales:
    en:
      language: English
      flag: gb
    es:
      language: Español
      flag: es
    fr:
      language: Français
      flag: fr
    ja:
      language: 日本語
      flag: jp
    pt:
      language: Português
      flag: pt
    tr:
      language: Türkçe
      flag: tr
    zh-CN:
      language: 中文
      flag: cn

