apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ include "ird.webapp.fullname" . }}
   labels:
    app.kubernetes.io/name: {{ include "ird.webapp.name" . }}
    helm.sh/chart: {{ include "ird.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ird.webapp.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ird.webapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        #must run as root user
        runAsUser: 0
      containers:
        - name: {{ include "ird.webapp.name" . }}
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
          imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
          command: ["bash", "-c"]
          # args: ["bundle exec rails db:migrate && bundle exec rails assets:precompile && bundle exec thor index:reindex && ./bin/rails server"]
          args: ["bundle exec rails db:migrate && bundle exec rails assets:precompile && ./bin/rails server"]
          resources:
            requests:
              {{- with .Values.webapp.resources.requests }}
              memory:  {{ .memory }}
              cpu: {{ .cpu }}
              {{- end }}
            limits:
              {{- with .Values.webapp.resources.limits }}
              memory: {{ .memory }}
              cpu: {{ .cpu }}
              {{- end }}
          ports:
            - containerPort: {{ .Values.webapp.service.containerPort }}
          startupProbe:
            httpGet:
              path: /up
              port: {{ .Values.webapp.service.containerPort }}
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: OPENSEARCH_URL
              value: {{ .Values.opensearch.url }}
            - name: JOBS_MAX_THREADS
              value: "1"
            - name: HEADER_BANNER_MESSAGE
              value: {{ .Values.banner_message }}
            - name: ALLOW_TEST_USER_ACCOUNTS_WITHOUT_VERIFICATION
              value: {{ quote .Values.allow_user_accounts_without_verification }}
            - name: TEST_USER_ACCOUNTS
              value: {{ quote .Values.test_user_accounts }}
            - name: RAILS_LOG_LEVEL
              value: {{ quote .Values.webapp.logLevel }}
          envFrom:
            - configMapRef:
                name: ird-env-configmap
            - secretRef:
                name: ird-secrets
        - name: {{ include "ird.jobs.name" . }}
          image: "{{ .Values.jobs.image.repository }}:{{ .Values.jobs.image.tag }}"
          imagePullPolicy: {{ .Values.jobs.image.pullPolicy }}
          command: ["bash", "-c"]
          # args: ["bundle exec rails solid_queue:start"]
          args: ["bundle exec rails db:migrate && ./bin/jobs"]
          resources:
            requests:
              {{- with .Values.jobs.resources.requests }}
              memory:  {{ .memory }}
              cpu: {{ .cpu }}
              {{- end }}
            limits:
              {{- with .Values.jobs.resources.limits }}
              memory: {{ .memory }}
              cpu: {{ .cpu }}
              {{- end }}
          env:
            - name: OPENSEARCH_URL
              value: {{ .Values.opensearch.url }}
            - name: RAILS_MAX_THREADS
              value: "1"
            - name: JOBS_MAX_THREADS
              value: "5"
            - name: RAILS_LOG_LEVEL
              value: {{ quote .Values.jobs.logLevel }}
          envFrom:
            - configMapRef:
                name: ird-env-configmap
            - secretRef:
                name: ird-secrets