apiVersion: v1
kind: Service
metadata:
  name: {{ include "ird.webapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ird.webapp.name" . }}
    helm.sh/chart: {{ include "ird.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
   app.kubernetes.io/name: {{ include "ird.webapp.name" . }}
   app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http-web-server
    protocol: TCP
    port: {{ .Values.webapp.service.port }}
    targetPort: {{ .Values.webapp.service.containerPort }}