name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  push_to_registry:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Dotenv Action
      id: dotenv
      uses: falti/dotenv-action@v1.1.4
      with:
        path: './DockerfileApp.env'
        export-variables: true
        keys-case: upper

    - name: Log in to Docker Hub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
      with:
        context: .
        file: './DockerfileApp'
        build-args: |
          IRD_APP_VERSION=${{ steps.dotenv.outputs.ird_app_version }}
        push: true
        tags: "antleaf/ird_app:${{ steps.dotenv.outputs.ird_app_version }}"
      
